- name: Things to do on all k8s nodes
  hosts: kubernetes

  tasks:
  - name: Update and upgrade
    ansible.builtin.apt:
      update_cache: yes
      upgrade: "yes"
    become: true
  - name: Install common utilities
    ansible.builtin.apt:
      update_cache: yes
      name:
      - vim
      - git
      - wget
      - software-properties-common
      - lsb-release
      - ca-certificates
    become: true
  - name: Disable swap for current session
    command: swapoff -a
    become: true
  - name: Disable swap permanently, persist reboots
    replace:
      path: /etc/fstab
      regexp: '^(\s*)([^#\n]+\s+)(\w+\s+)swap(\s+.*)$'
      replace: '#\1\2\3swap\4'
      backup: yes
  - name: Enable overlay module
    community.general.modprobe:
      name: overlay
      state: present
      persistent: present
    become: true
  - name: Enable br_netfilter module
    community.general.modprobe:
      name: br_netfilter
      state: present
      persistent: present
    become: true
  - name: Modify kubernetes.conf
    ansible.builtin.blockinfile:
      path: /etc/sysctl.d/kubernetes.conf
      create: true
      block: |
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1
        net.ipv4.ip_forward = 1
    become: true
  - name: Run sysctl --system
    ansible.builtin.shell:
      cmd: |
        systemctl --system
    become: true
  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /etc/apt/keyrings
      state: directory
    become: true
  - name: One way to avoid apt_key once it is removed from your distro
    block:
      - name: containerd | no apt key
        ansible.builtin.get_url:
          url: https://download.docker.com/linux/ubuntu/gpg
          dest: /etc/apt/keyrings/docker.asc
        become: true
      - name: containerd | apt source
        ansible.builtin.apt_repository:
          repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
          state: present
        become: true
  - name: Install containerd
    ansible.builtin.apt:
      update_cache: yes
      name:
      - containerd.io
    become: true
  - name: Run containerd command
    ansible.builtin.shell:
      cmd: |
        containerd config default | tee /etc/containerd/config.toml
    become: true
  - name: Modify config.toml
    ansible.builtin.replace:
      path: /etc/containerd/config.toml
      regexp: 'SystemdCgroup = false'
      replace: 'SystemdCgroup = true'
    become: true
  - name: Restart containerd
    ansible.builtin.systemd:
      state: restarted
      name: containerd
    become: true
